type CleaningMethod = 'Trimmed' | 'Bone-in' | 'Boneless' | 'Chopped';

type MeatData = {
  id: number;
  name: string;
  image: string;
  pricePerKg: number;
  minWeight: number; // in kg
  description: string;
  cleaningOptions: CleaningMethod[];
};

const meatData: MeatData[] = [
  {
    id: 1,
    name: 'Beef Ribeye Steak',
    image: 'https://masskaronline.com/uploads/images/items/Al%20Anaam%20Fresh%20Local%20Lamb.jpg',
    pricePerKg: 80,
    minWeight: 0.5,
    description: 'Tender and juicy, ideal for grilling or pan-searing.',
    cleaningOptions: ['Trimmed', 'Bone-in'],
  },
  {
    id: 2,
    name: 'Lamb Chops',
    image: 'https://masskaronline.com/uploads/images/items/Al%20Anam%20Egyptian%20Chilled%20Beef%20With%20Bone.jpg',
    pricePerKg: 95,
    minWeight: 0.4,
    description: 'Flavorful lamb chops, perfect for grilling or baking.',
    cleaningOptions: ['Chopped', 'Bone-in'],
  },
  {
    id: 3,
    name: 'Chicken Breast',
    image: 'https://masskaronline.com/uploads/images/items/Al%20Anam%20Kazakistan%20Chilled%20Lamb%20Whole%20Per%20Kg.jpg',
    pricePerKg: 35,
    minWeight: 0.3,
    description: 'Lean and healthy cut, ideal for stir-fry or grilling.',
    cleaningOptions: ['Boneless', 'Trimmed'],
  },
  {
    id: 4,
    name: 'Goat Meat',
    image: 'https://masskaronline.com/uploads/images/items/Al%20Anam%20Tanzania%20Chilled%20Lamb%28Barbari%29.jpg',
    pricePerKg: 70,
    minWeight: 1.0,
    description: 'Fresh goat meat for curries and stews.',
    cleaningOptions: ['Chopped', 'Boneless'],
  },
  {
    id: 5,
    name: 'Turkey Thighs',
    image: 'https://masskaronline.com/uploads/images/items/Al%20Anam%20local%20Lamb%20with%20Bone.jpg',
    pricePerKg: 40,
    minWeight: 0.8,
    description: 'Juicy turkey thighs, perfect for roasting.',
    cleaningOptions: ['Trimmed', 'Boneless'],
  },
  {
    id: 6,
    name: 'Minced Beef',
    image: 'https://masskaronline.com/uploads/images/items/Arabic%20Lamb%20Mince.jpg',
    pricePerKg: 55,
    minWeight: 0.5,
    description: 'Lean minced beef for burgers or meatballs.',
    cleaningOptions: ['Chopped'],
  },
  {
    id: 7,
    name: 'Chicken Wings',
    image: 'https://masskaronline.com/uploads/images/items/Arabic%20Lamb%20With%20Bone.jpg',
    pricePerKg: 28,
    minWeight: 0.5,
    description: 'Crispy and perfect for frying or BBQ.',
    cleaningOptions: ['Bone-in', 'Trimmed'],
  },
  {
    id: 8,
    name: 'Duck Breast',
    image: 'https://masskaronline.com/uploads/images/items/Arabic%20Local%20Lamb%20Boneless.jpg',
    pricePerKg: 60,
    minWeight: 0.4,
    description: 'Rich, flavorful meat ideal for fine dining.',
    cleaningOptions: ['Trimmed', 'Boneless'],
  },
  {
    id: 9,
    name: 'Veal Cutlets',
    image: 'https://masskaronline.com/uploads/images/items/Beef%20Bone.jpg',
    pricePerKg: 85,
    minWeight: 0.3,
    description: 'Delicate and tender, great for schnitzel.',
    cleaningOptions: ['Boneless', 'Trimmed'],
  },
  {
    id: 10,
    name: 'Beef Brisket',
    image: 'https://masskaronline.com/uploads/images/items/Beef%20Liver.jpg',
    pricePerKg: 75,
    minWeight: 1.0,
    description: 'Perfect for slow cooking or smoking.',
    cleaningOptions: ['Trimmed', 'Chopped'],
  },
  {
    id: 11,
    name: 'Chicken Drumsticks',
    image: 'https://masskaronline.com/uploads/images/items/Camel%20Meat%20Boneless.jpg',
    pricePerKg: 30,
    minWeight: 0.6,
    description: 'Great for frying, baking, or grilling.',
    cleaningOptions: ['Bone-in', 'Trimmed'],
  },
  {
    id: 12,
    name: 'Mutton Leg',
    image: 'https://masskaronline.com/uploads/images/items/Camel%20Meat%20Kofta%20Price%204Pcs.jpg',
    pricePerKg: 68,
    minWeight: 1.2,
    description: 'Hearty and full of flavor, ideal for roasting.',
    cleaningOptions: ['Boneless', 'Chopped'],
  },
  {
    id: 13,
    name: 'Pork Loin',
    image: 'https://masskaronline.com/uploads/images/items/Camel%20Meat%20Steak.jpg',
    pricePerKg: 50,
    minWeight: 0.8,
    description: 'Tender cut perfect for roasting or slicing.',
    cleaningOptions: ['Trimmed', 'Boneless'],
  },
  {
    id: 14,
    name: 'Camel Meat',
    image: 'https://masskaronline.com/uploads/images/items/Indian%20Buffalo%20Boneless%20.jpg',
    pricePerKg: 60,
    minWeight: 1.0,
    description: 'Traditional meat with a rich, unique flavor.',
    cleaningOptions: ['Chopped', 'Boneless'],
  },
  {
    id: 15,
    name: 'Chicken Liver',
    image: 'https://masskaronline.com/uploads/images/items/Fresh%20Chicken%20800gm.jpg',
    pricePerKg: 25,
    minWeight: 0.3,
    description: 'Delicate and iron-rich organ meat.',
    cleaningOptions: ['Trimmed', 'Chopped'],
  },
  {
    id: 16,
    name: 'Beef Tongue',
    image: 'https://masskaronline.com/uploads/images/items/Indian%20Mutton%20Chilled.jpg',
    pricePerKg: 48,
    minWeight: 0.6,
    description: 'Soft and tender, great for braising.',
    cleaningOptions: ['Trimmed', 'Chopped'],
  },
  {
    id: 17,
    name: 'Rabbit Meat',
    image: 'https://masskaronline.com/uploads/images/items/Local%20Beef%20Boneless.jpg',
    pricePerKg: 70,
    minWeight: 0.9,
    description: 'Lean and delicate, perfect for stews.',
    cleaningOptions: ['Chopped', 'Boneless'],
  },
  {
    id: 18,
    name: 'Beef Short Ribs',
    image: 'https://masskaronline.com/uploads/images/items/Pakistan%20Chilled%20Beef%20Boneless.jpg',
    pricePerKg: 78,
    minWeight: 1.0,
    description: 'Great for BBQ or slow braising.',
    cleaningOptions: ['Bone-in', 'Trimmed'],
  },
  {
    id: 19,
    name: 'Chicken Gizzards',
    image: 'https://masskaronline.com/uploads/images/items/Pakistan%20Chilled%20Mutton.jpg',
    pricePerKg: 22,
    minWeight: 0.4,
    description: 'Chewy, flavorful, and full of texture.',
    cleaningOptions: ['Chopped', 'Trimmed'],
  },
  {
    id: 20,
    name: 'Quail Meat',
    image: 'https://masskaronline.com/uploads/images/items/Tanzania%20Chilled%20Goat%20Per%20Kg.jpg',
    pricePerKg: 90,
    minWeight: 0.25,
    description: 'Exquisite taste, suitable for gourmet dishes.',
    cleaningOptions: ['Boneless', 'Trimmed'],
  },
];

export default meatData;
